apiVersion: v1
kind: Namespace
metadata:
  name: landingpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebros-landing-page-api
  namespace: landingpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebros-landing-page-api
  template:
    metadata:
      labels:
        app: cerebros-landing-page-api
    spec:
      containers:
      - name: cerebros-landing-page-api
        image: davidt101/cerebros-03-2025-landing-page-apis:dev-0015
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_PASSWORD
          value: "[PLACEHOLDER]"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cerebros-landing-page-api-service
  namespace: landingpage
spec:
  selector:
    app: cerebros-landing-page-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: landingpage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: landingpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17.4-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "[PLACEHOLDER]"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: landingpage
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cerebros-landing-ingress-v2
  namespace: landingpage
  annotations:
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: devcerebroslandingspageapis.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cerebros-landing-page-api-service
            port:
              number: 8000
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
  namespace: landingpage
spec:
  domains:
    - devcerebroslandingspageapis.com
